### PR TITLE
Use zombie to simulate a browser logging into the tfl admin area

### PR DESCRIPTION
**Pull request by charliedowler**
Hey,

My proposed fix, it's quite a big change. It'd be best to try and keep the API the same but this makes the old balance method redundant.

I suppose if you were thinking of adding more methods later, this would be a problem.

Let me know what you think.

Cheers,
Charlie

### CODE REVIEW

**Comment by bencevans** [comment]
Hi @charliedowler is this working for you? I'm getting...

```
/home/bencevans/Development/bencevans/node-oyster/node_modules/zombie/node_modules/bluebird/js/main/promise.js:866
            throw e;
                  ^
TypeError: Cannot use 'in' operator to search for 'compareDocumentPosition' in null
    at /home/bencevans/Development/bencevans/node-oyster/node_modules/zombie/node_modules/jsdom/node_modules/nwmatcher/src/nwmatcher-noqsa.js:306:43
    at module.exports (/home/bencevans/Development/bencevans/node-oyster/node_modules/zombie/node_modules/jsdom/node_modules/nwmatcher/src/nwmatcher-noqsa.js:37:7)
    at addNwmatcher (/home/bencevans/Development/bencevans/node-oyster/node_modules/zombie/node_modules/jsdom/lib/jsdom/selectors/index.js:6:27)
    at HTMLDocument.<anonymous> (/home/bencevans/Development/bencevans/node-oyster/node_modules/zombie/node_modules/jsdom/lib/jsdom/selectors/index.js:18:29)
    at HTMLDocument.querySelectorAll (/home/bencevans/Development/bencevans/node-oyster/node_modules/zombie/node_modules/jsdom/lib/jsdom/level1/core.js:63:53)
    at Browser.queryAll (/home/bencevans/Development/bencevans/node-oyster/node_modules/zombie/lib/zombie/browser.js:369:26)
    at Browser.field (/home/bencevans/Development/bencevans/node-oyster/node_modules/zombie/lib/zombie/browser.js:616:17)
    at Browser.fill (/home/bencevans/Development/bencevans/node-oyster/node_modules/zombie/lib/zombie/browser.js:646:18)
    at /home/bencevans/Development/bencevans/node-oyster/lib/oyster.js:26:13
    at tryCatch1 (/home/bencevans/Development/bencevans/node-oyster/node_modules/zombie/node_modules/bluebird/js/main/util.js:45:21)
```

**Comment by charliedowler** [comment]
Hmm, I did get that once, couldn't re-create it.

Zombie also hangs for a second before closing, I could look into a different headless browser.

Cheers

**Comment by bencevans** [comment]
Odd. I opted for using request and pretending to be a browser instead of
running a headless browser to keep it light on resources and as quick as
possible so think may be better off sticking with the same approach.

**Comment by charliedowler** [comment]
No worries, I was also aiming to keep using request but I'm stumped by TFL's changes.
Thanks for considering it,
Charlie

**Comment by bencevans** [comment]
I know, I wish they'd just provide an API already! :P

**Pull request closed without merging**
